name: Rubocop
on: [push]
jobs:
  analyze-rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Rubocop start
        run: |
          bundle install
          bundle exec rubocop
